name: jalseva
description: A smart social media for disasters
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  getwidget: ^2.0.4
  image_picker: ^1.0.4
  get: ^4.6.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/drop.png
    - assets/spsc_bottom_img.png
    - assets/title.png
    - assets/male.png
    - assets/google_maps.png
